messages:
  prefix: "&7[&6L&bB&7]"
  reload: "&aПлагин успешно перезагружен &e[{time} ms]"


parameters:
  frequency-save-db: 10 # в секундах

blocks:
  BOOKSHELF:
    max-stack-size: 1
    inventory-title: "&0▶ КНИЖНАЯ ПОЛКА"
    inventory-size: 36
    allowed-items:
      - BOOK
      - WRITABLE_BOOK
      - WRITTEN_BOOK
      - ENCHANTED_BOOK